Update svn keywords on Java sources and scripts.

diff --git a/scripts/ioi_soak_test b/scripts/ioi_soak_test
--- a/scripts/ioi_soak_test
+++ b/scripts/ioi_soak_test
@@ -5,14 +5,14 @@ set ioi_address = "ioi_linux"
 set ioi_port = 8472
 set exposure_length_list = "1000 2000 5000 10000 30000 60000 120000"
 set exposure_count_list = "1 3 5 9"
-if ( -r /home/dev/bin/ioi/test/SendMultrunCommand.class ) then
-	set multrun_dir = /home/dev/bin/ioi/test/
-else if ( -r /icc/bin/ioi/test/SendMultrunCommand.class ) then
-	set multrun_dir = /icc/bin/ioi/test/
-else 
-	echo "Failed to find directory containing SendMultrunCommand.class."
-	exit 1
-endif
+#if ( -r /home/dev/bin/ioi/test/SendMultrunCommand.class ) then
+#	set multrun_dir = /home/dev/bin/ioi/test/
+#else if ( -r /icc/bin/ioi/test/SendMultrunCommand.class ) then
+#	set multrun_dir = /icc/bin/ioi/test/
+#else 
+#	echo "Failed to find directory containing SendMultrunCommand.class."
+#	exit 1
+#endif
 set done = 0
 set config_count = 0
 set multrun_count = 0
@@ -23,7 +23,8 @@ while ( ${done} == 0 )
 		foreach exposure_length ( ${exposure_length_list} )
 			date
 			echo "Sending config command"
-			java ngat.ioi.test.SendConfigCommand -address ${ioi_address} -ioiport ${ioi_port} -x 1 -y 1 -filter J -serverport 7383
+			java ngat.ioi.test.SendConfigCommand -address ${ioi_address} -ioiport ${ioi_port} -x 1 -y 1 -filter J 
+#-issserverport 7383
 			set config_status = $status
 			if( ${config_status} != 0 ) then
 				echo "Config ${config_count} failed."
@@ -32,8 +33,9 @@ while ( ${done} == 0 )
 			@ config_count ++
 			date
 			echo "Sending Multrun command ${exposure_length} ms x ${exposure_count}"
-			cd ${multrun_dir}
-			java SendMultrunCommand -address ${ioi_address} -ccsport ${ioi_port} -exposureLength ${exposure_length} -exposureCount ${exposure_count} -serverport 7383
+			#cd ${multrun_dir}
+			java ngat.ioi.test.SendMultrunCommand -address ${ioi_address} -ioiport ${ioi_port} -exposureLength ${exposure_length} -exposureCount ${exposure_count} 
+#-issserverport 7383
 			set multrun_status = $status
 			if( ${multrun_status} != 0 ) then
 				echo "Multrun ${multrun_count} (${exposure_length} ms x ${exposure_count}) failed."
