Changes to ABORTImplementation to allow for successful aborts returning an error message. Some changes to default properties. ioi_tar_install tries to shutdown ASIC.

diff --git a/scripts/ioi_tar_install b/scripts/ioi_tar_install
--- a/scripts/ioi_tar_install
+++ b/scripts/ioi_tar_install
@@ -53,6 +53,18 @@ else
     echo "killhup not found:FAILED to stop running processess."
 endif
 #
+# Power down the ASIC
+# We can only do this AFTER killing the robotic software,
+# as this keeps the connectrion open and the IDL Socket Server will
+# only service one connection at a time.
+#
+java ngat.ioi.command.PowerDownASICCommand ioi_win 5000
+set java_status = $status
+if( ${java_status} != 0 ) then
+    echo "Failed to power down ASIC."
+    exit 1
+endif
+#
 # Kill nfs server - /icc/tmp is usually mounted for the rcs machine
 #
 echo "Stopping NFS server (/icc/tmp is exported)..."
